"""
Alerts Router
--------------
Endpoints for FinanceIQ's proactive alert system.

GET  /alerts              → list all alerts (filterable)
GET  /alerts/stats        → alert statistics
GET  /alerts/{alert_id}   → get a specific alert
PUT  /alerts/{alert_id}/read → mark alert as read
PUT  /alerts/read-all     → mark all alerts as read
"""

from fastapi import APIRouter, HTTPException, Depends, Query
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from typing import Optional

from app.services.alert_service import alert_service
from app.services import auth_service

router = APIRouter()
bearer = HTTPBearer(auto_error=False)


def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(bearer)
) -> dict:
    if not credentials:
        return {"sub": "anonymous", "role": "analyst"}
    payload = auth_service.decode_token(credentials.credentials)
    if not payload:
        raise HTTPException(status_code=401, detail="Invalid token.")
    return payload


@router.get("/alerts")
async def get_alerts(
    ticker:      Optional[str]  = Query(default=None, description="Filter by ticker e.g. AAPL"),
    severity:    Optional[str]  = Query(default=None, description="CRITICAL, HIGH, MEDIUM, LOW"),
    unread_only: bool           = Query(default=False, description="Only unread alerts"),
    limit:       int            = Query(default=50, ge=1, le=200),
    user:        dict           = Depends(get_current_user),
):
    """
    Returns proactive alerts generated by the monitoring system.

    Alerts are generated automatically when:
    - A contradiction is detected between documents
    - Severe risk keywords are found (going concern, material adverse, etc.)
    - Forward guidance changes between documents
    - A new document is uploaded and analyzed

    Filter by ticker to see alerts for a specific company.
    Filter by severity to prioritize CRITICAL and HIGH alerts.
    """
    alerts = alert_service.get_all(
        ticker      = ticker,
        severity    = severity,
        unread_only = unread_only,
        limit       = limit,
    )

    return {
        "total":   len(alerts),
        "filters": {
            "ticker":      ticker,
            "severity":    severity,
            "unread_only": unread_only,
        },
        "alerts":  alerts,
    }


@router.get("/alerts/stats")
async def get_alert_stats(user: dict = Depends(get_current_user)):
    """
    Returns aggregate alert statistics.
    Used by the dashboard to show unread count and severity breakdown.
    """
    return alert_service.get_stats()


@router.get("/alerts/{alert_id}")
async def get_alert(
    alert_id: str,
    user:     dict = Depends(get_current_user),
):
    """Get a specific alert by ID."""
    alert = alert_service.get_by_id(alert_id)
    if not alert:
        raise HTTPException(
            status_code=404,
            detail=f"Alert {alert_id} not found."
        )
    return alert


@router.put("/alerts/{alert_id}/read")
async def mark_alert_read(
    alert_id: str,
    user:     dict = Depends(get_current_user),
):
    """Mark a specific alert as read."""
    success = alert_service.mark_read(alert_id)
    if not success:
        raise HTTPException(
            status_code=404,
            detail=f"Alert {alert_id} not found."
        )
    return {"message": f"Alert {alert_id} marked as read."}


@router.put("/alerts/read-all")
async def mark_all_read(
    ticker: Optional[str] = Query(default=None),
    user:   dict          = Depends(get_current_user),
):
    """Mark all alerts as read, optionally filtered by ticker."""
    alert_service.mark_all_read(ticker=ticker)
    return {
        "message": "All alerts marked as read.",
        "ticker_filter": ticker,
    }